---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ptp-operator-subscription
  namespace: openshift-ptp
spec:
  channel: "${channel}"
  name: ptp-operator
  source: "${subscription_source}"
  sourceNamespace: openshift-marketplace
