---
apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ${BOND_NAME}
spec:
  desiredState:
    interfaces:
    - name: ${BOND_NAME}
      type: bond
      ipv4:
        auto-dns: false
        auto-gateway: false
        auto-routes: false
        dhcp: true
        enabled: true
      state: up
      link-aggregation:
        mode: balance-rr
        options:
          miimon: '140'
        slaves:
        - ${MASTER_NIC}
        - ${SLAVE_NIC}
